### ISSUE TITLE
Net::SIP wants to establish a IPv6 connection

### ISSUE THREAD

**Issue by lazyfrosch** [NETWAYS/check_sip_call#1]
Even when to global IPv6 address is existing locally.

    cannot find local IP when connecting to 2001:ab7:0:0:0:0:0:1 at /usr/share/perl5/Net/SIP/Leg.pm line 117.

Probably we need to setup the outgoing leg ourselves?

Workaround: Use IPv4 address

**Comment by martialblog** [comment]
Added hint to README
